#!/usr/bin/env python3
"""
k-NN Classifier for Enzyme Class Prediction using ProtSEC Distance Matrices

This script implements a k-NN classifier using the scikit-learn library in Python. 
The classifier is trained on protein sequence embeddings generated by the ProtSEC model, 
and it can be used to predict the enzyme class of new protein sequences based on their embeddings.

The input consists of pairwise distance matrices that are converted to similarity matrices 
by computing 1-Distance, and enzyme class annotations at multiple levels (EC1, EC2, EC3, EC All).
"""

import numpy as np
import pandas as pd
import argparse
import os
from pathlib import Path
from typing import Tuple, Dict, List, Optional
import warnings
from Bio import SeqIO

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import precision_recall_fscore_support, roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.multiclass import OneVsRestClassifier
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings('ignore')


def load_distance_matrix(file_path: str) -> Tuple[np.ndarray, List[str]]:
    """
    Load distance matrix from CSV file and extract protein IDs.
    
    Args:
        file_path: Path to the distance matrix CSV file
        
    Returns:
        Tuple of (distance_matrix, protein_ids)
    """
    print(f"Loading distance matrix from: {file_path}")
    
    df = pd.read_csv(file_path, index_col=0)
    protein_ids = df.index.tolist()
    distance_matrix = df.values
    
    print(f"Loaded distance matrix with shape: {distance_matrix.shape}")
    print(f"Number of proteins: {len(protein_ids)}")
    
    return distance_matrix, protein_ids


def distance_to_similarity(distance_matrix: np.ndarray) -> np.ndarray:
    """
    Convert distance matrix to similarity matrix using 1 - distance.
    
    Args:
        distance_matrix: Pairwise distance matrix
        
    Returns:
        Similarity matrix
    """
    print("Converting distance matrix to similarity matrix...")
    similarity_matrix = 1 - distance_matrix
    
    # Ensure diagonal is 1 (self-similarity)
    np.fill_diagonal(similarity_matrix, 1.0)
    
    # Ensure non-negative similarities
    similarity_matrix = np.clip(similarity_matrix, 0, 1)
    
    print(f"Similarity matrix statistics:")
    print(f"  Min: {similarity_matrix.min():.4f}")
    print(f"  Max: {similarity_matrix.max():.4f}")
    print(f"  Mean: {similarity_matrix.mean():.4f}")
    
    return similarity_matrix


def load_annotations(file_path: str, protein_ids: List[str]) -> pd.DataFrame:
    """
    Load enzyme class annotations and filter for available proteins.
    
    Args:
        file_path: Path to the annotation CSV file
        protein_ids: List of protein IDs from distance matrix
        
    Returns:
        DataFrame with filtered annotations
    """
    print(f"Loading annotations from: {file_path}")
    
    annotations = pd.read_csv(file_path)
    print(f"Total annotations loaded: {len(annotations)}")
    
    # Filter annotations for proteins in our distance matrix
    available_proteins = set(protein_ids)
    annotations_filtered = annotations[annotations['Entry'].isin(available_proteins)].copy()
    
    print(f"Annotations after filtering: {len(annotations_filtered)}")
    print(f"Available EC levels: {[col for col in annotations_filtered.columns if col.startswith('EC')]}")
    
    return annotations_filtered


def prepare_data(similarity_matrix: np.ndarray, protein_ids: List[str], 
                annotations: pd.DataFrame, ec_level: str = 'EC1') -> Tuple[np.ndarray, np.ndarray, List[str]]:
    """
    Prepare training data by aligning similarity matrix with annotations.
    
    Args:
        similarity_matrix: Protein similarity matrix
        protein_ids: List of protein IDs
        annotations: Enzyme class annotations
        ec_level: EC level to predict ('EC1', 'EC2', 'EC3', 'EC All')
        
    Returns:
        Tuple of (features, labels, filtered_protein_ids)
    """
    print(f"Preparing data for EC level: {ec_level}")
    print(f"Input similarity matrix shape: {similarity_matrix.shape}")
    print(f"Number of protein IDs: {len(protein_ids)}")
    print(f"Annotations shape: {annotations.shape}")
    print(f"Available columns in annotations: {list(annotations.columns)}")
    
    # Check if EC level exists in annotations
    if ec_level not in annotations.columns:
        print(f"ERROR: EC level '{ec_level}' not found in annotations!")
        print(f"Available EC columns: {[col for col in annotations.columns if 'EC' in col]}")
        return np.array([]), np.array([]), []
    
    # Create mapping from protein ID to index
    protein_to_idx = {protein_id: idx for idx, protein_id in enumerate(protein_ids)}
    print(f"First 10 protein IDs from matrix: {protein_ids[:10]}")
    
    # Filter annotations to only include proteins in our matrix
    available_annotations = annotations[annotations['Entry'].isin(protein_ids)].copy()
    print(f"Annotations after filtering by protein IDs: {len(available_annotations)}")
    
    if len(available_annotations) == 0:
        print("ERROR: No annotations match protein IDs in distance matrix!")
        print(f"First 10 entries in annotations: {annotations['Entry'].head(10).tolist()}")
        print(f"First 10 protein IDs in matrix: {protein_ids[:10]}")
        return np.array([]), np.array([]), []
    
    # Check for non-null EC values
    non_null_ec = available_annotations[pd.notna(available_annotations[ec_level])]
    print(f"Annotations with non-null {ec_level}: {len(non_null_ec)}")
    
    if len(non_null_ec) == 0:
        print(f"ERROR: No proteins have valid {ec_level} values!")
        print(f"Sample {ec_level} values: {available_annotations[ec_level].head(10).tolist()}")
        return np.array([]), np.array([]), []
    
    # Get indices for available proteins
    indices = []
    labels = []
    filtered_protein_ids = []
    
    for _, row in available_annotations.iterrows():
        protein_id = row['Entry']
        if protein_id in protein_to_idx and pd.notna(row[ec_level]):
            idx = protein_to_idx[protein_id]
            indices.append(idx)
            labels.append(row[ec_level])
            filtered_protein_ids.append(protein_id)
    
    print(f"Found {len(indices)} proteins with valid data")
    
    if len(indices) == 0:
        print("ERROR: No valid proteins found after all filtering!")
        return np.array([]), np.array([]), []
    
    # Extract similarity features for available proteins
    features = similarity_matrix[np.ix_(indices, indices)]
    labels = np.array(labels)
    
    print(f"Final dataset size: {len(features)} proteins")
    print(f"Features shape: {features.shape}")
    print(f"Number of unique classes: {len(np.unique(labels))}")
    print(f"Class distribution:")
    unique_labels, counts = np.unique(labels, return_counts=True)
    for label, count in zip(unique_labels, counts):
        print(f"  {label}: {count}")
    
    return features, labels, filtered_protein_ids


def train_knn_classifier(X_train: np.ndarray, y_train: np.ndarray, 
                        X_test: np.ndarray, y_test: np.ndarray,
                        k_values: List[int] = [3, 5, 7, 9, 11]) -> Dict:
    """
    Train k-NN classifier with different k values and evaluate performance.
    
    Args:
        X_train: Training features (similarity matrix)
        y_train: Training labels
        X_test: Test features
        y_test: Test labels
        k_values: List of k values to try
        
    Returns:
        Dictionary with results for each k value
    """
    print("Training k-NN classifiers...")
    
    results = {}
    best_k = None
    best_score = 0
    
    for k in k_values:
        print(f"\nTraining k-NN with k={k}")
        
        # Train classifier
        knn = KNeighborsClassifier(n_neighbors=k, metric='precomputed')
        
        # Convert similarity to distance for sklearn (sklearn expects distance matrix)
        X_train_dist = 1 - X_train
        X_test_dist = 1 - X_test
        
        knn.fit(X_train_dist, y_train)
        
        # Predictions
        y_pred = knn.predict(X_test_dist)
        y_pred_proba = knn.predict_proba(X_test_dist)
        
        # Calculate metrics
        accuracy = accuracy_score(y_test, y_pred)
        precision, recall, f1, _ = precision_recall_fscore_support(y_test, y_pred, average='weighted')
        
        # Cross-validation score
        cv_scores = cross_val_score(knn, X_train_dist, y_train, cv=3, scoring='accuracy')
        
        results[k] = {
            'classifier': knn,
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'cv_mean': cv_scores.mean(),
            'cv_std': cv_scores.std(),
            'predictions': y_pred,
            'probabilities': y_pred_proba,
            'classification_report': classification_report(y_test, y_pred)
        }
        
        print(f"  Accuracy: {accuracy:.4f}")
        print(f"  F1-score: {f1:.4f}")
        print(f"  CV Score: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")
        
        if accuracy > best_score:
            best_score = accuracy
            best_k = k
    
    print(f"\nBest k value: {best_k} with accuracy: {best_score:.4f}")
    results['best_k'] = best_k
    
    return results


def plot_results(results: Dict, output_dir: str, ec_level: str):
    """
    Create visualizations of classifier performance.
    
    Args:
        results: Results dictionary from train_knn_classifier
        output_dir: Directory to save plots
        ec_level: EC level being predicted
    """
    os.makedirs(output_dir, exist_ok=True)
    
    # Extract k values and metrics
    k_values = [k for k in results.keys() if isinstance(k, int)]
    accuracies = [results[k]['accuracy'] for k in k_values]
    f1_scores = [results[k]['f1_score'] for k in k_values]
    cv_means = [results[k]['cv_mean'] for k in k_values]
    cv_stds = [results[k]['cv_std'] for k in k_values]
    
    # Performance vs k plot
    plt.figure(figsize=(12, 8))
    
    plt.subplot(2, 2, 1)
    plt.plot(k_values, accuracies, 'o-', label='Test Accuracy')
    plt.plot(k_values, cv_means, 's-', label='CV Accuracy')
    plt.fill_between(k_values, np.array(cv_means) - np.array(cv_stds), 
                     np.array(cv_means) + np.array(cv_stds), alpha=0.3)
    plt.xlabel('k value')
    plt.ylabel('Accuracy')
    plt.title(f'k-NN Performance vs k ({ec_level})')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    plt.subplot(2, 2, 2)
    plt.plot(k_values, f1_scores, 'o-', color='orange')
    plt.xlabel('k value')
    plt.ylabel('F1-score')
    plt.title(f'F1-score vs k ({ec_level})')
    plt.grid(True, alpha=0.3)
    
    # Confusion matrix for best k
    best_k = results['best_k']
    best_result = results[best_k]
    
    # Get unique labels for confusion matrix
    all_labels = np.concatenate([best_result['predictions'], 
                                list(results[k_values[0]]['classifier'].classes_)])
    unique_labels = np.unique(all_labels)
    
    plt.subplot(2, 2, (3, 4))
    # Note: We need actual test labels to create confusion matrix
    # This is a placeholder - you'll need to pass y_test to this function
    plt.text(0.5, 0.5, f'Best k: {best_k}\nAccuracy: {best_result["accuracy"]:.4f}\nF1-score: {best_result["f1_score"]:.4f}', 
             ha='center', va='center', transform=plt.gca().transAxes, fontsize=12)
    plt.title(f'Best Model Performance ({ec_level})')
    plt.axis('off')
    
    plt.tight_layout()
    plt.savefig(f'{output_dir}/knn_performance_{ec_level}.png', dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Performance plots saved to: {output_dir}/knn_performance_{ec_level}.png")


def save_predictions(results: Dict, protein_ids: List[str], output_file: str, ec_level: str):
    """
    Save predictions to CSV file.
    
    Args:
        results: Results dictionary
        protein_ids: List of protein IDs
        output_file: Output CSV file path
        ec_level: EC level being predicted
    """
    best_k = results['best_k']
    best_result = results[best_k]
    
    predictions_df = pd.DataFrame({
        'Protein_ID': protein_ids,
        f'Predicted_{ec_level}': best_result['predictions'],
        'Confidence': np.max(best_result['probabilities'], axis=1)
    })
    
    predictions_df.to_csv(output_file, index=False)
    print(f"Predictions saved to: {output_file}")


def main():
    """Main function with command-line interface."""
    parser = argparse.ArgumentParser(
        description="k-NN Classifier for Enzyme Class Prediction using ProtSEC Distance Matrices",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s --train_matrix ./fastas/all_test_seqs_score_matrix.csv --train_annotations protein_train.csv --test_matrix ./fastas/30_protein_test_score_matrix.csv --test_annotations 30_protein_test.csv --ec_level EC1

  %(prog)s --train_matrix ./fastas/all_test_seqs_score_matrix.csv --train_annotations protein_train.csv --test_matrix ./fastas/30_protein_test_score_matrix.csv --test_annotations 30_protein_test.csv --ec_level "EC All" --output_dir results_ec_all
        """
    )
    
    parser.add_argument('--train_matrix', required=True, 
                       help='Training distance matrix CSV file')
    parser.add_argument('--train_annotations', required=True,
                       help='Training annotations CSV file')
    parser.add_argument('--test_matrix', required=True,
                       help='Test distance matrix CSV file')
    parser.add_argument('--test_annotations', required=True,
                       help='Test annotations CSV file')
    parser.add_argument('--ec_level', default='EC1',
                       choices=['EC1', 'EC2', 'EC3', 'EC All'],
                       help='EC level to predict')
    parser.add_argument('--k_values', nargs='+', type=int, default=[3, 5, 7, 9, 11],
                       help='k values to try')
    parser.add_argument('--output_dir', default='knn_results',
                       help='Output directory for results')
    
    args = parser.parse_args()
    
    # Create output directory
    os.makedirs(args.output_dir, exist_ok=True)
    
    print("="*60)
    print("k-NN Classifier for Enzyme Class Prediction")
    print("="*60)
    
    try:
        # Load training data
        print("\n" + "="*40)
        print("LOADING TRAINING DATA")
        print("="*40)
        
        train_dist_matrix, train_protein_ids = load_distance_matrix(args.train_matrix)
        train_similarity_matrix = distance_to_similarity(train_dist_matrix)
        train_annotations = load_annotations(args.train_annotations, train_protein_ids)
        
        X_train, y_train, train_filtered_ids = prepare_data(
            train_similarity_matrix, train_protein_ids, train_annotations, args.ec_level
        )
        
        if len(X_train) == 0:
            print("ERROR: No training data available after filtering!")
            return 1
        
        # Load test data
        print("\n" + "="*40)
        print("LOADING TEST DATA")
        print("="*40)
        
        test_dist_matrix, test_protein_ids = load_distance_matrix(args.test_matrix)
        test_similarity_matrix = distance_to_similarity(test_dist_matrix)
        test_annotations = load_annotations(args.test_annotations, test_protein_ids)
        
        X_test, y_test, test_filtered_ids = prepare_data(
            test_similarity_matrix, test_protein_ids, test_annotations, args.ec_level
        )
        
        if len(X_test) == 0:
            print("ERROR: No test data available after filtering!")
            return 1
        
        # Train and evaluate classifiers
        print("\n" + "="*40)
        print("TRAINING AND EVALUATION")
        print("="*40)
        
        results = train_knn_classifier(X_train, y_train, X_test, y_test, args.k_values)
        
        # Print detailed results
        print("\n" + "="*40)
        print("DETAILED RESULTS")
        print("="*40)
        
        best_k = results['best_k']
        best_result = results[best_k]
        
        print(f"\nBest k-NN Classifier (k={best_k}):")
        print(f"  Accuracy: {best_result['accuracy']:.4f}")
        print(f"  Precision: {best_result['precision']:.4f}")
        print(f"  Recall: {best_result['recall']:.4f}")
        print(f"  F1-score: {best_result['f1_score']:.4f}")
        print(f"  CV Score: {best_result['cv_mean']:.4f} ± {best_result['cv_std']:.4f}")
        
        print(f"\nClassification Report:")
        print(best_result['classification_report'])
        
        # Save results
        print("\n" + "="*40)
        print("SAVING RESULTS")
        print("="*40)
        
        # Save predictions
        predictions_file = f"{args.output_dir}/predictions_{args.ec_level.replace(' ', '_')}.csv"
        save_predictions(results, test_filtered_ids, predictions_file, args.ec_level)
        
        # Save detailed results
        results_file = f"{args.output_dir}/detailed_results_{args.ec_level.replace(' ', '_')}.txt"
        with open(results_file, 'w') as f:
            f.write(f"k-NN Classifier Results for {args.ec_level}\n")
            f.write("="*50 + "\n\n")
            f.write(f"Training data: {args.train_matrix}\n")
            f.write(f"Test data: {args.test_matrix}\n")
            f.write(f"EC level: {args.ec_level}\n\n")
            
            for k in args.k_values:
                result = results[k]
                f.write(f"k={k}:\n")
                f.write(f"  Accuracy: {result['accuracy']:.4f}\n")
                f.write(f"  Precision: {result['precision']:.4f}\n")
                f.write(f"  Recall: {result['recall']:.4f}\n")
                f.write(f"  F1-score: {result['f1_score']:.4f}\n")
                f.write(f"  CV Score: {result['cv_mean']:.4f} ± {result['cv_std']:.4f}\n\n")
            
            f.write(f"Best k: {best_k}\n\n")
            f.write("Classification Report (Best Model):\n")
            f.write(best_result['classification_report'])
        
        print(f"Detailed results saved to: {results_file}")
        
        # Create plots
        plot_results(results, args.output_dir, args.ec_level)
        
        print("\n" + "="*60)
        print("ANALYSIS COMPLETE")
        print("="*60)
        print(f"All results saved to: {args.output_dir}")
        
    except Exception as e:
        print(f"Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    exit(main())
